### PR TITLE
UI for service

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- implement ui for service management
- 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- add management for service in the dashboard
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
> /status in-review

Please cc me again once it is ready for review.

**Comment by warjiang** [comment]
> > /status in-review
> 
> Please cc me again once it is ready for review.

@RainbowMango i've rebased the code and recheck the feature locally, let's move forward.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
