### PR TITLE
Refactor dashboard

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
review whether current implementation works as expected, make more suggestion and feedback

**Which issue(s) this PR fixes**:
Fixes #
None

**Special notes for your reviewer**:
@RainbowMango 
@samzong 

**Does this PR introduce a user-facing change?**:

```release-note
- brand new structure for dashboard, including backend and frontend.
- management of clusters, including accessing new cluster、remove cluster from karmada contro-plane
- management of propagationpolicy, including create、delete、update propagationpolicy
- management of namepace, including create、delete namespace, support annotation of `skipAutoPropagation`
- management of workload  partially(only deployment now)
- new docs, including todos.md for recoding process of refactor,  DEVELOPMENT.md for new developers, meanwhile a user-guide for beginners, which will implement the quickstart tutorial mentioned on the karmada website
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/assign 
Is there a document or guide for people to test it?

**Comment by warjiang** [comment]
Currently there is no guide for user, only one development guide. I've made this PR in WIP status, and user guide will be finished soon.

**Comment by RainbowMango** [comment]
Oh, right, please cc me once it is ready for review.

Thanks for your hard work! Take care!

**Comment by RainbowMango** [comment]
This comment is just for testing the new Prowbot, regarding to https://github.com/karmada-io/karmada/issues/4637.

/priority important-soon

**Comment by warjiang** [comment]
> Oh, right, please cc me once it is ready for review.
> 
> Thanks for your hard work! Take care!

@RainbowMango hi, the ugly doc is comming 🤣 (The shell scripts only tested on debian12)

I've made a very simple user-guide(follow the [link](https://github.com/warjiang/dashboard/blob/refactor/dashboard/docs/user-guide.md ) to have a preview version ) which do the same thing like [karmada quickstart](https://karmada.io/docs/get-started/nginx-example) but all operations are finished in karmada dashboard. The new dashboard still have many works to do till now [todos of dashboard ](https://github.com/warjiang/dashboard/blob/refactor/dashboard/todos.md).
Currently I've already finished overview of karmada，management of cluster、propagationpolicy and part of multicloud resource(like namespace、 deployment of workload).  What need to note is that, I directly used the editor instead of forms in current implementation, but it  will be gradually improved in subsequent iterations.

**Comment by RainbowMango** [comment]
Just tried  as per the linked user-guide, it looks great! Thanks you!
I can contribute to this user-guide as well after this PR, such as we probably need to forward the traffic from the machine to kind-cluster. Here is what we I did:
```
-bash-5.0# kubectl port-forward -n karmada-system services/karmada-dashboard-web --address 0.0.0.0 8000:8000
Forwarding from 0.0.0.0:8000 -> 8000
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000
```

**Comment by RainbowMango** [comment]
/retitle Refactor dashboard

@warjiang Seems we are ready to go?
Let me know if you are going to tidy your commits such as group them to meaningful commits.

**Comment by warjiang** [comment]
> Just tried as per the linked user-guide, it looks great! Thanks you! I can contribute to this user-guide as well after this PR, such as we probably need to forward the traffic from the machine to kind-cluster. Here is what we I did:
> 
> ```
> -bash-5.0# kubectl port-forward -n karmada-system services/karmada-dashboard-web --address 0.0.0.0 8000:8000
> Forwarding from 0.0.0.0:8000 -> 8000
> Handling connection for 8000
> Handling connection for 8000
> Handling connection for 8000
> ```

Yeah, it seems that we do the same thing without any communication before 😆 .  Maybe we should provide alternative ways for end-users, like ingress、nodeport or use port-forward as you metioned above.

**Comment by warjiang** [comment]
> /retitle Refactor dashboard
> 
> @warjiang Seems we are ready to go? Let me know if you are going to tidy your commits such as group them to meaningful commits.

I will rebase these commits this week.

**Comment by RainbowMango** [comment]
> Maybe we should provide alternative ways for end-users, like ingress、nodeport or use port-forward as you metioned above.

Yeah, we can talk about it after this PR.
The first thing we should decide is `should we expose the dashboard by default`, by leveraging ingress or node port.

In addition, Port-forward seems dedicated to developers who are using kind to host the dashboard. We just need to document it.

**Comment by RainbowMango** [comment]
also cc @samzong

**Comment by warjiang** [comment]
> > /retitle Refactor dashboard
> > @warjiang Seems we are ready to go? Let me know if you are going to tidy your commits such as group them to meaningful commits.
> 
> I will rebase these commits this week.

@RainbowMango Rebasing git commits and replacing personal info with karmada org info already done.

**Comment by RainbowMango** [comment]
Here we go!
/lgtm
/approve

**Pull request merged**
