### PR TITLE
feature: add service management

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- implement management for service
- export rest api for frontend web-ui
- 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
How many other resource types we are going to add? Is there a list for it? 
With the list, I can see the process.

**Comment by warjiang** [comment]
I list the related resource in the https://github.com/karmada-io/dashboard/issues/76
image

Till now, we only left ingress resource under the service before the first release.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
