### PR TITLE
implementing feature of config for karmada dashboard

### LINKED ISSUE #74: Config for karmada dashboard
**What would you like to be added**:
Add configuration system for karmada dashboard
**Why is this needed**:
When developing Karmada Dashboard, we need a configuration system to control the behavior of the dashboard. For instance, we may want to temporarily hide menu items that are in alpha state and only make them visible to users once they are fully in the GA (General Availability) state. In the context of Kubernetes, by default, we aim to leverage Kubernetes’s infrastructure to achieve the goal of configuration system. This involves using ConfigMap and Secret as the underlying storage providers for storing system configurations. Additionally, we aim to achieve an effect similar to [Reloader](https://github.com/stakater/Reloader), where configuration changes can be directly obtained in the application after they are updated.
The overview of the configuration system works like following diagram:
image

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**

/kind feature
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #74 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- add config for dashboard config, admin can control sidebar menu by editing the `karmada-dashboard-configmap` configmap.
```

### CODE REVIEW

**Comment by warjiang** [comment]
/retitle implementing feature of config for karmada dashboard

**Comment by RainbowMango** [comment]
You might need to resolve the conflicts and rebase.

**Comment by warjiang** [comment]
> You might need to resolve the conflicts and rebase.

@RainbowMango The conflict already been resolved 🏁

**Review by RainbowMango — APPROVED** [review]
Given the structure of this ConfigMap lacks a standard API-style definition, this may bring challenges like, when making changes to the definition, the backward compatibility might be break.

But, for now we can move forward, and wait and see if we need an API for this configuration.

/lgtm
/approve

**Pull request merged**
