### PR TITLE
Bump Karmada dependencies to v1.11.0

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
This PR just updates Karmada dependencies to the latest v1.11.0.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by warjiang** [comment]
@RainbowMango the following lines should be removed if we bump karmada to v1.11.0

https://github.com/karmada-io/dashboard/blob/d0e68747821c32b106aa4785db90e5ea37c0c44d/cmd/api/app/routes/cluster/accesscluster.go#L323-L325


the related commit in the karmada👉🏻： https://github.com/karmada-io/karmada/commit/a0ace65395c950240381a00ca22eb38b6eefd07a

**Comment by RainbowMango** [comment]
Updated and pushed, thanks.
In addition, I think we should build a CI for those things, so I created #102 to track this.

**Comment by warjiang** [comment]
> Updated and pushed, thanks. In addition, I think we should build a CI for those things, so I created #102 to track this.

+1

**Pull request merged**
