### PR TITLE
feat: update locale file format & add extra log

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
keep the format of locale files to avoid too many changes in locale files. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by warjiang** [comment]
need to rebase the code

**Comment by warjiang** [comment]
code rebase done, plz recheck it again @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
