### PR TITLE
charts: add the missing dashboard configmap

### LINKED ISSUE #120: The overview page crashed: `TypeError: i is not iterable`
**What happened**:

Screenshot 2024-09-12 at 09 53 44
Screenshot 2024-09-11 at 16 35 53

After successfully deploying Karmada and the dashboard, and logging into the dashboard successfully, when redirecting to the overview page, the page crashes immediately. All components are running normally, and the API returns responses as expected:

Screenshot 2024-09-12 at 09 53 38

**How to reproduce it (as minimally and precisely as possible)**:

The issue should be reproducible in a newly deployed environment.

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.11
- Karmada Dashboard version: latest

/cc @warjiang

### PR DESCRIPTION
**Pull request by iawia002**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix #120

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

/cc @warjiang @RainbowMango

### CODE REVIEW

**Comment by RainbowMango** [comment]
```
> @karmada/dashboard@1.0.0 build /home/runner/work/dashboard/dashboard/ui/apps/dashboard
> tsc && vite build

/home/runner/work/dashboard/dashboard/ui/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/native.js:59
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4[82](https://github.com/karmada-io/dashboard/actions/runs/10826402935/job/30037300368?pr=124#step:5:83)8). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```
Is there anything we can do with it?

/retest
Give it another try

**Comment by warjiang** [comment]
> ```
> > @karmada/dashboard@1.0.0 build /home/runner/work/dashboard/dashboard/ui/apps/dashboard
> > tsc && vite build
> 
> /home/runner/work/dashboard/dashboard/ui/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/native.js:59
> 		throw new Error(
> 		      ^
> 
> Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4[82](https://github.com/karmada-io/dashboard/actions/runs/10826402935/job/30037300368?pr=124#step:5:83)8). Please try `npm i` again after removing both package-lock.json and node_modules directory.
> ```
> 
> Is there anything we can do with it?
> 
> /retest Give it another try

retest command seems not work. 
I'll check it the task(build-frontend) locally

**Comment by iawia002** [comment]
I found the solution, not sure why we haven't encountered this problem before, but the CI is happy now.

**Comment by RainbowMango** [comment]
> retest command seems not work.

Tracked by #125

**Comment by iawia002** [comment]
> ```
> pnpm install --filter @karmada/dashboard
> pnpm run dashboard:build
> ```

Cool, it works. PTAL @warjiang

**Pull request merged**
