### PR TITLE
Add UI Components

### PR DESCRIPTION
**Pull request by ada2468**
The PR includes layout, header, sidebar, body and etc.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
The PR includes layout, header, sidebar, body, sidebar list, containers and etc. These are the basic building blocks of our pages.

**Which issue(s) this PR fixes**:
No. This PR adds independent UI components and should not have breaking changes.

**Special notes for your reviewer**:
"None"

**Does this PR introduce a user-facing change?**:
"None"

```release-note

```

Signed-off-by: @ada2468 <jx2161@nyu.edu>

### CODE REVIEW

**Comment by RainbowMango** [comment]
@ada2468 You made it!
Please sign your commit according to https://github.com/karmada-io/dashboard/pull/22/checks?check_run_id=7351658474.

Could you please add some descriptions for people know how to run the patch locally?

cc @chinmaym07 too.

**Comment by jxiang1995** [comment]
Sure, I'm working on it.

**Comment by ada2468** [comment]
Sure! Working on it!

**Comment by jxiang1995** [comment]
How to run:
1. Pull request locally
2. run "npm install"
3. run  "npm run test" to see jest unit test result.
4. run "npm run start", navigate to "http://localhost:3000/test" to see the demo.

Note: MUI global theme changes are in PR#23. This PR doesn't contain global styling. 

Signed-off-by: Jun Xiang <jx2161@nyu.edu>

**Comment by ada2468** [comment]
How to run:

Pull request locally and follow the steps:
1. run "npm install"
2. run "npm run test" to see jest unit test result.
3. run "npm run start", navigate to "http://localhost:3000/playground" to see the demo.

Note: MUI global theme changes are in PR#23. This PR doesn't contain global styling.

Signed-off-by: Jun Xiang <jx2161@nyu.edu>

**Pull request closed without merging**
