### PR TITLE
Added DataTable Component

### PR DESCRIPTION
**Pull request by ShwetKhatri2001**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
The PR includes a reusable Table component to be used on different pages with different types of data. 
This is the first iteration of the component. It will be modified further with API integration and required functionalities working.
It is static and currently implementing this [Figma Design](https://www.figma.com/file/lEDkjr4gdIn35BSi1hXAGT/Karmada?node-id=42%3A18) ( Overview Page - iteration 7 frame ).

**Which issue(s) this PR fixes**:
It's a general component useful for different pages of the entire application.

**Special notes for your reviewer**:
@RainbowMango I'm attaching the screenshot of the developed UI, which was taken by using the component on a new page just for testing. Although, it is not used in any of the pages currently. So, the PR is just having its implementation.

karmada table component

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

Signed-off-by: @ShwetKhatri2001

### CODE REVIEW

**Comment by RainbowMango** [comment]
Seems it's a `static` page now, I can't tell if works as expected, I guess we'd better build a real page with it.

**Comment by ShwetKhatri2001** [comment]
I need some resources to understand the API response. So that I can make the component dynamic with the actual data.

**Comment by RainbowMango** [comment]
What kind of resources do you need?

**Comment by ada2468** [comment]
@ShwetKhatri2001 
Check out this file. I'm using this one as API design spec.
https://github.com/karmada-io/karmada/blob/master/api/openapi-spec/swagger.json

**Comment by ShwetKhatri2001** [comment]
@ada2468 Thanks for the help, but we will have different types of data passed to this component and the pages where the component is going to be used are not developed/merged yet. so, the component  can't be completely dynamic or finalized currently according to me. @RainbowMango what's your thought on this?

**Comment by RainbowMango** [comment]
/close
Thank you for your effort on this, we are currently working with another approach.

**Pull request closed without merging**
