### PR TITLE
UI for configmap management

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
1. add store management, we use zustand now
2. ui for configmap management
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- implement management for configmap under the config
- introduct zustand as store management
```

### CODE REVIEW

**Comment by warjiang** [comment]
This PR should be reviewed after
- https://github.com/karmada-io/dashboard/pull/83
- https://github.com/karmada-io/dashboard/pull/85

**Comment by RainbowMango** [comment]
> This PR should be reviewed after
> 
> * [configmap manage #83](https://github.com/karmada-io/dashboard/pull/83)
> * [feat: update err-check cond, add method for create unstructured resou… #85](https://github.com/karmada-io/dashboard/pull/85)

The two PRs get merged, but you have to rebase and resolve the conflicts.

**Comment by warjiang** [comment]
> > This PR should be reviewed after
> > 
> > * [configmap manage #83](https://github.com/karmada-io/dashboard/pull/83)
> > * [feat: update err-check cond, add method for create unstructured resou… #85](https://github.com/karmada-io/dashboard/pull/85)
> 
> The two PRs get merged, but you have to rebase and resolve the conflicts.

I'll solve conflicts asap~.

**Comment by warjiang** [comment]
> > This PR should be reviewed after
> > 
> > * [configmap manage #83](https://github.com/karmada-io/dashboard/pull/83)
> > * [feat: update err-check cond, add method for create unstructured resou… #85](https://github.com/karmada-io/dashboard/pull/85)
> 
> The two PRs get merged, but you have to rebase and resolve the conflicts.

After rebase main, this PR seems much smaller than before 😄 .
@RainbowMango  Let's move forward~

**Pull request merged**
