### PR TITLE
fix: correct translation string usage and JSX formatting in Popup confirm

### PR DESCRIPTION
**Pull request by axif0**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The translation and string concatenation in the Popconfirm component to ensure proper rendering of the confirmation message and handling of translations.

**Which issue(s) this PR fixes**:
Fixes # N/A

**Special notes for your reviewer**: N/A

**Does this PR introduce a user-facing change?**:
N/A

```release-note

```

Signed-off-by: axif <muhamadasif570@gmail.com>

### CODE REVIEW

**Comment by warjiang** [comment]
Thanks for your translation, it's useful, but now we're developing a i18n cli tools for automatically translating, but now the cli in the status of WIP cc @chouchongYHMing, it will works in the mode of hybird including manual mode and auto mode, some of your translation is useful, but some are not we expected, like 
image
we expected this kind of translation like `${i18nInstance.t('xxx', r.objectMeta.name)}` and the map for `xxx` will be like `集群%1删除成功` for cn and `Cluster%1delete successfully` for en.
I think we can pend this pr, and renew it when the i18n-cli has any update

**Review by samzong — COMMENTED** [review]
The contribution time is a bit long, I suggest merging it first (so more people can easily participate), the subsequent upgrade of i18n-cli will not affect this part.

/lgtm

**Comment by RainbowMango** [comment]
@axif0 The conflicts should be resolved before moving forward.

**Comment by warjiang** [comment]
@axif0 can you rebase the code, it seems that we can move forward

**Comment by warjiang** [comment]
@axif0 There are some conflict with the main branch, can you resolve the conflict, and recheck the PR ?

**Comment by axif0** [comment]
Hello, as this pr a bit too old for target branch. And I see we already fixed i18n tools. Should I close the PR?

**Pull request closed without merging**
