### PR TITLE
update url of yaml in README

### PR DESCRIPTION
**Pull request by zhouqunjie-cs**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
update url of yaml in README

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
By the way, the image now has been published to `swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-dashboard:latest`, the `karmada-dashboard.yaml` should be updated as well.

**Comment by RainbowMango** [comment]
Hi @zhouqunjie-cs Please sign your commits, and here is a guide for you:
https://github.com/karmada-io/dashboard/pull/9/checks?check_run_id=4772225924

Please cc me after that, thanks.

**Comment by zhouqunjie-cs** [comment]
Hi @RainbowMango  commits have been signed and the image has also been updated.

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
