### PR TITLE
feat: add api for cronjob resources

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind design

**What this PR does / why we need it**:
Add api for cronjob resource management.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by warjiang** [comment]
api for cronjob depends on job, plz  waiting for #111

**Comment by warjiang** [comment]
> Thanks for your hard work! Appreciated, you can rebase it now as #111 get merged.

Already rebase main branch, here we go~

**Review by RainbowMango — COMMENTED** [review]
/assign

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
