### PR TITLE
Added Login page

### LINKED ISSUE #10: [lfx-mentorship] Continue dashboard developing after onboarding
**What would you like to be added**:
The initial version of `karmada-dashboard` just getting on board, and more pages waiting for development.
Welcome front-end developers join us and contribute to this project!

**Goals**
- Design the prototype of the dashboard and the prototype will be placed in the repo.
- Split development tasks into small interaction items and make a plan to iterate the tasks.
  - Note: Not all items are required to be finished within the LFX cycle.
  - The mentor and the maintainers of this project will help figure out the scope that should be included in the LFX project.
- The CI(continuous integration) should be set up along with the dashboard development work.
- Enhance the documents, such as user guide/README.

> Note: 
> 1. The architecture of Karmada project is pretty similar to the Kubernetes, so it is recommended to investigate the [Kubernetes dashboard](https://github.com/kubernetes/dashboard) first.
> 2. The previous prototype might be not terribly helpful, we can design it from scratch.
> 3. The framework can be changed(such as ReactJs) as well if there is a need.

**Mentee**:
There are several mentees who applied to this project, but I can only select one fit(mentee) for this project(correct me if not right). All mentees are welcome to apply in the following LFX or GSoC cycles.

### PR DESCRIPTION
**Pull request by chinmaym07**
**What type of PR is this?**

/kind feature
/kind design
/kind documentation

**What this PR does / why we need it**:

This PR adds newly designed Login page to the karmada dashboard.

**Which issue(s) this PR fixes**:
Fixes #10 

**Special notes for your reviewer**:
1. Login through `Token` method works fine, I have tested it locally.
2. Facing some issue with Login through `Kubeconfig` file.

**Does this PR introduce a user-facing change?**:

```release-note
Added newly designed Login Page UI.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
> Facing some issue with Login through Kubeconfig file.

That's ok. We can fix that after this PR.

cc me when ready for review.

**Comment by chinmaym07** [comment]
/assign @rainbowmango

Yes sir we can fix the kubeconfig later. I have update the PR. It's ready for review
cc: @RainbowMango

**Comment by jhnine** [comment]
What is the reason for changing the framework?

**Comment by chinmaym07** [comment]
I have considered React for building the project on these points. 

- Fast client-side rendering.
- Good control of the data flow.
- Light-weight architecture.
- Extensibility and scalability.
- Large community support.
- JSX

**Comment by RainbowMango** [comment]
@chinmaym07 I haved created the branch, please help send the PR to the new-created branch `ng-dashboard-react`.

**Pull request closed without merging**
