### PR TITLE
ci: setup ci-workflow for PR

### LINKED ISSUE #102: Setup CI workflow for PR
**What would you like to be added**:

Setup a CI workflow to verify PR, at least it should verify the PR passes compile.

**Why is this needed**:
Currently a lack of CI workflow, some faults might be introduced like https://github.com/karmada-io/dashboard/pull/101#issuecomment-2326838136.

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- precheck build error when contributor submit PR 

some mock-case:
1. if contributor submit invalid goland code, like
    image
    the ci-workflow will report error like following:
    image

2. if contributor submit invalid frontend code, like
    image
    the ci-workflow will report error like following:
    image

**Which issue(s) this PR fixes**:
Fixes #102

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by warjiang** [comment]
!!! this pr based https://github.com/karmada-io/dashboard/pull/114
so we should resolve the pr#114

**Comment by warjiang** [comment]
> !!! this pr based #114 so we should resolve the [pr#114](https://github.com/karmada-io/dashboard/pull/114)

@RainbowMango already rebased code, plz check this PR again~

**Review by RainbowMango — COMMENTED** [review]
/assign
Don't have enough time today, probably tomorrow.

**Review by RainbowMango — COMMENTED** [review]
Generally looks good to me, Thanks.

**Comment by warjiang** [comment]
I've already add the suggestion and cleaned up the commit msg, here we go @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
